default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: take_dat_shit_development

test:
  <<: *default
  database: take_dat_shit_test

production:
  <<: *default
  database: take_dat_shit_development
